# Generated by Django 4.0.5 on 2024-12-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0023_bookingdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='departure_date',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='arrival_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_place', to='sample.touristplaces'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.buses'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='departure_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_place', to='sample.touristplaces'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.flights'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.tours'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='transportation_type',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Flight', 'Flight'), ('Tour', 'Tour')], default='Bus', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.user'),
        ),
    ]
