# Generated by Django 4.0.5 on 2024-12-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0024_remove_bookingdetails_arrival_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('seats_booked', models.PositiveIntegerField()),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.flights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.user')),
            ],
            options={
                'db_table': 'flight_booking_details',
            },
        ),
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
