# Generated by Django 4.0.5 on 2024-12-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0026_remove_flightbookingdetails_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusBookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.IntegerField()),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_reference', models.CharField(max_length=100, unique=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_bookings', to='sample.buses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_bookings', to='sample.user')),
            ],
            options={
                'db_table': 'bus_booking_details',
            },
        ),
    ]
