# Generated by Django 4.0.5 on 2024-12-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0028_remove_busbookingdetails_booking_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbookingdetails',
            name='seats_booked',
        ),
        migrations.RemoveField(
            model_name='busbookingdetails',
            name='total_fare',
        ),
    ]
